language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-mirage.sh
script:
- bash -ex .travis-certs.sh
- bash -ex .travis-mirage.sh
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - ocaml-base
    - ocaml-native-compilers
    - ocaml-compiler-libs
    - ocaml-interp
    - ocaml-base-nox
    - ocaml-nox
    - camlp4
    - camlp4-extra
    - time
    - libgmp-dev
env:
  - FORK_USER=talex5 FORK_BRANCH=containers2 OPAMYES=true OCAML_VERSION=4.01 OPAM_SWITCH=system OPAM_INIT=true MIRAGE_BACKEND=unix DHCP=no
